# Generated by Django 3.1.13 on 2021-10-07 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_work_out', '0001_create_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
    ]
